### ISSUE TITLE
Crashes when cloning active tab

### ISSUE THREAD

**Issue by Dimox** [icylace/CursorRuler#8] opened 2015-03-24 09:57 UTC
When I clonе active tab through ```File -> New View into File``` CursorRuler is crushes with the following errors:

```
Traceback (most recent call last):
  File "CursorRuler in c:\Programs\Sublime Text\Data\Installed Packages\CursorRuler.sublime-package", line 252, in on_command_mode_change
  File "CursorRuler in c:\Programs\Sublime Text\Data\Installed Packages\CursorRuler.sublime-package", line 241, in on_selection_modified
  File "c:\Programs\Sublime Text\sublime.py", line 183, in active_window
    return Window(sublime_api.active_window())
RuntimeError: maximum recursion depth exceeded
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

**Comment by icylace** [comment] 2015-03-24 14:23
Yes, that's strange.  Thank you for the bug report!  I'll try to investigate it soon.

**Comment by icylace** [comment] 2015-03-24 14:24
Oh, one more thing.  Are you running ST3 or ST2 ?

**Comment by Dimox** [comment] 2015-03-24 14:24
I'm using ST3.

**Comment by icylace** [comment] 2015-03-24 14:25
Okay, thanks.

**Comment by icylace** [comment] 2016-07-15 01:25
I'm currently running ST3 build 3118 and am unable to reproduce this error.  I'm going to close this ticket but if there's more info to help me reproduce the error please let me know.

**Closed by icylace** 2016-07-15 01:25 UTC
Labels: bug

**Comment by asoki** [comment] 2016-11-28 15:39
i using Cursor Ruler 1.1.6 (installed from package) with ST3 build 3126 on OSX 10.10.5, i get the following error when i clone the active tab:

    Traceback (most recent call last):
      File "CursorRuler in /Users/REDACTED/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 314, in on_command_mode_change
      File "CursorRuler in /Users/REDACTED/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 302, in on_selection_modified
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 296, in active_view
        return View(view_id)
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 707, in __init__
        self.selection = Selection(id)
    RuntimeError: maximum recursion depth exceeded
    error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
